import { Rule } from './types';

const ref = (label: string, url: string) => ({ label, url });

export const RULE_CATALOG: Rule[] = [
  { id: 'AGT-001', title: 'Lethal Trifecta', severity: 'critical', description: 'Composite: sensitive-data read + untrusted ingestion + outbound exfil capability.', fileTypes: ['auto','cursor','claude','agents-md','aider','mcp'], references: [ref('Simon Willison lethal trifecta','https://simonwillison.net/2025/Jun/16/the-lethal-trifecta/'), ref('OWASP LLM06:2025','https://genai.owasp.org/llmrisk/llm062025-excessive-agency/'), ref('OWASP ASI01','https://owasp.org/www-project-top-10-for-agentic-applications/')], remediation: 'Constrain capabilities so all three legs cannot coexist. Add explicit deny rules for secret paths, restrict untrusted fetch, and remove unrestricted outbound or shell/network paths.' },
  { id: 'AGT-002', title: 'Hardcoded Secrets', severity: 'critical', description: 'Plaintext tokens, API keys, passwords, or bearer secrets detected.', fileTypes: ['auto','cursor','claude','agents-md','aider','mcp'], references: [ref('OWASP LLM02:2025','https://genai.owasp.org/llmrisk/llm022025-sensitive-information-disclosure/'), ref('CWE-798','https://cwe.mitre.org/data/definitions/798.html')], remediation: 'Replace literals with env expansion (for example `${VAR}`), rotate leaked values, and keep secret material out of version control.' },
  { id: 'AGT-003', title: 'Untrusted MCP Server', severity: 'critical', description: 'MCP server source appears untrusted, insecure, or vulnerable.', fileTypes: ['auto','cursor','claude','mcp'], references: [ref('CVE-2025-6514','https://nvd.nist.gov/vuln/detail/CVE-2025-6514'), ref('CurXecute CVE-2025-54135','https://nvd.nist.gov/vuln/detail/CVE-2025-54135'), ref('MCPoison CVE-2025-54136','https://nvd.nist.gov/vuln/detail/CVE-2025-54136')], remediation: 'Pin MCP server versions, require trusted registries, and avoid plaintext HTTP MCP endpoints.' },
  { id: 'AGT-004', title: 'Auto-Run Without Sandbox', severity: 'critical', description: 'Automation bypasses approvals or sandbox checks.', fileTypes: ['auto','cursor','claude','aider'], references: [ref('OWASP LLM06','https://genai.owasp.org/llmrisk/llm062025-excessive-agency/'), ref('CVE-2025-54135','https://nvd.nist.gov/vuln/detail/CVE-2025-54135')], remediation: 'Disable bypass/always-yes modes and require explicit user approvals for high-risk tools.' },
  { id: 'AGT-005', title: 'Invisible Unicode in Instructions', severity: 'critical', description: 'Hidden Unicode ranges can conceal prompt-injection instructions.', fileTypes: ['auto','agents-md','cursor','claude'], references: [ref('AWS Unicode smuggling','https://aws.amazon.com/blogs/security/defending-llm-applications-against-unicode-character-smuggling/'), ref('Cisco Unicode Tag Prompt Injection','https://blogs.cisco.com/security/unicode-tag-prompt-injection'), ref('ASCII Smuggler','https://embracethered.com/blog/posts/2024/hiding-and-finding-text-with-unicode-tags/')], remediation: 'Strip invisible Unicode characters and normalize config text before execution.' },
  { id: 'AGT-006', title: 'Overly Broad Filesystem Access', severity: 'high', description: 'Filesystem permissions are too broad.', fileTypes: ['auto','cursor','claude','aider'], references: [ref('CWE-732','https://cwe.mitre.org/data/definitions/732.html')], remediation: 'Scope read/edit permissions to project subdirectories instead of root/home globs.' },
  { id: 'AGT-007', title: 'Missing Secrets Deny Pattern', severity: 'high', description: 'No explicit deny list for common secret files/paths.', fileTypes: ['auto','cursor','claude','aider'], references: [ref('Claude permissions guide','https://www.petefreitag.com/blog/claude-code-permissions/')], remediation: 'Add deny entries for `.env*`, `secrets/`, `.aws`, `.ssh`, `*.pem`, `.netrc`, and env diff/cat shell commands.' },
  { id: 'AGT-008', title: 'Network Without Domain Allowlist', severity: 'high', description: 'Network tools allowed without explicit domain restrictions.', fileTypes: ['auto','cursor','claude','aider','mcp'], references: [ref('OWASP LLM05','https://genai.owasp.org/llmrisk/llm052025-improper-output-handling/')], remediation: 'Allow only explicit domains and block generic curl/wget/nc patterns.' },
  { id: 'AGT-009', title: 'Shell + Network Combo', severity: 'high', description: 'Shell access combined with network capabilities.', fileTypes: ['auto','cursor','claude','aider','mcp'], references: [ref('Agents Rule of Two','https://openai.com')], remediation: 'Separate shell and network capabilities; force human approval when both are required.' },
  { id: 'AGT-010', title: 'MCP Mutation Without Re-Approval', severity: 'high', description: 'Project MCP config mutation risk; CODEOWNERS re-approval may be missing.', fileTypes: ['auto','cursor','claude','mcp'], references: [ref('CVE-2025-54136','https://nvd.nist.gov/vuln/detail/CVE-2025-54136')], remediation: 'Protect MCP config files with CODEOWNERS and mandatory review.' },
  { id: 'AGT-011', title: 'Dangerous MCP Command', severity: 'high', description: 'MCP command/args include RCE or reverse-shell signatures.', fileTypes: ['auto','cursor','claude','mcp'], references: [ref('CWE-78','https://cwe.mitre.org/data/definitions/78.html')], remediation: 'Remove shell-evaluated commands and ban reverse-shell primitives (`nc -e`, `/dev/tcp`, `curl|sh`).' },
  { id: 'AGT-012', title: 'Hooks Run Untrusted Commands', severity: 'high', description: 'Hooks execute interpolated or untrusted shell input.', fileTypes: ['auto','claude','aider','cursor'], references: [ref('CWE-78','https://cwe.mitre.org/data/definitions/78.html')], remediation: 'Treat hook input as untrusted; use fixed commands and sanitize arguments.' },
  { id: 'AGT-013', title: 'SSL Verification Disabled', severity: 'high', description: 'TLS verification disabled via settings/env or insecure URLs.', fileTypes: ['auto','claude','aider','mcp','cursor'], references: [ref('CWE-295','https://cwe.mitre.org/data/definitions/295.html')], remediation: 'Enable TLS verification and require HTTPS for all remote endpoints.' },
  { id: 'AGT-014', title: 'Unpinned MCP Versions', severity: 'medium', description: 'MCP dependencies are unpinned.', fileTypes: ['auto','cursor','claude','mcp'], references: [ref('Supply chain best practice','https://owasp.org/www-project-software-component-verification-standard/')], remediation: 'Pin package and image versions (no `@latest`, no `:latest`).' },
  { id: 'AGT-015', title: 'Plaintext Sensitive Env Names', severity: 'medium', description: 'Sensitive env variable names have literal values.', fileTypes: ['auto','cursor','claude','mcp','aider'], references: [ref('OWASP Secrets Management','https://owasp.org/www-project-secrets-management-cheat-sheet/')], remediation: 'Use `${VAR}` placeholders or secure secret stores for sensitive env keys.' },
  { id: 'AGT-016', title: 'Auto-Commit Without Verify', severity: 'medium', description: 'Auto-commit enabled while verification/approval safeguards are off.', fileTypes: ['auto','aider'], references: [ref('Aider safety posture','https://aider.chat')], remediation: 'Disable auto-commit or enforce commit verification checks.' },
  { id: 'AGT-017', title: 'Trivially Weak Rules File', severity: 'medium', description: 'Rules text too short or lacking normative safety constraints.', fileTypes: ['auto','agents-md','cursor','claude'], references: [ref('Policy hardening guidance','https://owasp.org')], remediation: 'Expand rules with explicit MUST/NEVER constraints, tool scope, and approval boundaries.' },
  { id: 'AGT-018', title: 'Self-Modifying Rules', severity: 'medium', description: 'Rules allow changing governance/config policy files.', fileTypes: ['auto','agents-md','cursor','claude'], references: [ref('OWASP ASI06','https://owasp.org/www-project-top-10-for-agentic-applications/')], remediation: 'Prohibit autonomous edits to rule files, `.git/`, and permission settings.' },
  { id: 'AGT-019', title: 'Missing Output Filter', severity: 'low', description: 'No output filtering/sanitization for rendered links/images.', fileTypes: ['auto','claude','cursor','agents-md'], references: [ref('EchoLeak CVE-2025-32711','https://nvd.nist.gov/vuln/detail/CVE-2025-32711')], remediation: 'Add strict output sanitization and URL/media allowlists when rendering tool output.' },
  { id: 'AGT-020', title: 'Untrusted Skill Scripts', severity: 'low', description: 'Skill script metadata lacks trust anchoring or license info.', fileTypes: ['auto','claude'], references: [ref('Skill supply chain guidance','https://owasp.org')], remediation: 'Require author allowlists, license fields, and script integrity pinning.' },
  { id: 'AGT-021', title: '.env Not in Ignore Files', severity: 'low', description: 'Sensitive file patterns not ignored across repo ignore files.', fileTypes: ['auto','aider','cursor','claude'], references: [ref('Git ignore patterns','https://git-scm.com/docs/gitignore')], remediation: 'Add `.env*`, private keys, and certs to ignore files across all tooling.' },
  { id: 'AGT-022', title: 'Telemetry Enabled', severity: 'info', description: 'Telemetry/anonymous analytics enabled in agent tooling.', fileTypes: ['auto','claude','cursor'], references: [ref('Privacy best practices','https://owasp.org')], remediation: 'Disable telemetry in local/dev environments for sensitive projects.' }
];
